version: "3.7"

services:
  rng-api:
    image: dockerfundamentals/rng-api
    environment:
      - Logging__LogLevel__Default=Debug
    ports:
      - "8087:80"
    networks:
      - app-net

  rng-web:
    image: dockerfundamentals/rng-web
    environment:
      - Logging__LogLevel__Default=Debug
      - RngApi__Url=http://rng-api/rng
    ports:
      - "8088:80"
    networks:
      - app-net

networks:
  app-net:
