services:
  rng-api:
    ports:
      - "8289:80"

  rng-web:
    ports:
      - "8290:80"

secrets:
  dotnet-logging:
    file: ./config/prod/logging.json
  rng-api:
    file: ./config/prod/api/override.json
  rng-web:
    file: ./config/prod/web/override.json
