name: RNG App Docker Image Weekly Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

env:
  RELEASE: 21.05
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}     

      - name: Build and push with tag ${{ env.RELEASE }}-${{ env.BUILD_NUMBER }}
        working-directory: labs/compose-build/rng
        run: |
          docker-compose -f docker-compose.yml -f docker-compose-build.yml build --pull
          docker-compose -f docker-compose.yml -f docker-compose-build.yml push
